/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paradise;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import paradise.objets.SQL_Outil;

/**
 *
 * @author Younouss boré
 */
public class Enregistrement extends javax.swing.JFrame {

    /**
     * Creates new form Enregistrement
     */
    public static int ticketNumber=0;
    
    public Enregistrement() {
        initComponents();
        remplir_bloc();
        
    }
    
    public SQL_Outil C1=new SQL_Outil("paradis");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        enregistrement_nom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        enregistrement_prenom = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        enregistrement_tel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        enregistrement_motif = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        enregistrement_block = new javax.swing.JComboBox<>();
        enregistrement_btn_enregistrer = new javax.swing.JButton();
        enregistrement_btn_annuler = new javax.swing.JButton();
        enregistrement_date = new com.toedter.calendar.JDateChooser();
        enregistrement_genre = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nom:");

        enregistrement_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrement_nomActionPerformed(evt);
            }
        });

        jLabel3.setText("Genre:");

        jLabel4.setText("date de naissance:");

        jLabel5.setText("Prenom:");

        enregistrement_prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrement_prenomActionPerformed(evt);
            }
        });

        jLabel6.setText("tel:");

        enregistrement_tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrement_telActionPerformed(evt);
            }
        });

        jLabel7.setText("Motif:");

        enregistrement_motif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrement_motifActionPerformed(evt);
            }
        });

        jLabel8.setText("bloc");

        enregistrement_block.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        enregistrement_block.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrement_blockActionPerformed(evt);
            }
        });

        enregistrement_btn_enregistrer.setText("Enregistrer");
        enregistrement_btn_enregistrer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enregistrement_btn_enregistrerMouseClicked(evt);
            }
        });

        enregistrement_btn_annuler.setText("Annuler");
        enregistrement_btn_annuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enregistrement_btn_annulerMouseClicked(evt);
            }
        });

        enregistrement_date.setNextFocusableComponent(enregistrement_motif);

        enregistrement_genre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "homme", "femme" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(enregistrement_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(enregistrement_genre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(enregistrement_block, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(enregistrement_date, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(enregistrement_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(enregistrement_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(enregistrement_motif, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(enregistrement_btn_enregistrer)
                        .addGap(75, 75, 75)
                        .addComponent(enregistrement_btn_annuler)
                        .addGap(224, 224, 224)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(enregistrement_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(enregistrement_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(enregistrement_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(enregistrement_genre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(enregistrement_block, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(enregistrement_motif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(enregistrement_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enregistrement_btn_enregistrer)
                    .addComponent(enregistrement_btn_annuler))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 34)); // NOI18N
        jLabel1.setText("Enregistrement");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(jLabel1)
                .addContainerGap(378, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enregistrement_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrement_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enregistrement_nomActionPerformed

    private void enregistrement_prenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrement_prenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enregistrement_prenomActionPerformed

    private void enregistrement_telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrement_telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enregistrement_telActionPerformed

    private void enregistrement_motifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrement_motifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enregistrement_motifActionPerformed

    private void enregistrement_blockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrement_blockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enregistrement_blockActionPerformed

    private void enregistrement_btn_enregistrerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enregistrement_btn_enregistrerMouseClicked
        // TODO add your handling code here:
        if(!enregistrement_nom.getText().equals("") && !enregistrement_prenom.getText().equals("") && !enregistrement_tel.getText().equals("") && !enregistrement_motif.getText().equals("")){
            if(enregister()){
                JOptionPane.showMessageDialog(this, "Patient Enregistrer", "enregistrer", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this, "Erreur d'enregistrement", "erreur", JOptionPane.CANCEL_OPTION);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Veuillez emplir les champs", "erreur", JOptionPane.CANCEL_OPTION);

        }
        
        
    }//GEN-LAST:event_enregistrement_btn_enregistrerMouseClicked

    private void enregistrement_btn_annulerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enregistrement_btn_annulerMouseClicked
        // TODO add your handling code here:
        SimpleDateFormat test=new SimpleDateFormat("dd-MM-yyyy");

        enregistrement_nom.setText("");
        enregistrement_prenom.setText("");
        enregistrement_tel.setText("");
        enregistrement_motif.setText("");
        System.out.println("Annuler");
        
        JOptionPane.showMessageDialog(this, "Enregistrement Annuler", "annuler", JOptionPane.CANCEL_OPTION);
    }//GEN-LAST:event_enregistrement_btn_annulerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Enregistrement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Enregistrement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Enregistrement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Enregistrement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Enregistrement().setVisible(true);
                
            }
        });
    }
    
    String[] fields=new String[5];
    String[] head=new String[5];
    
    public void remplir_bloc(){
        if(C1.try_connection()){
            ResultSet response=C1.simple_select("bloc");
           
            ArrayList<String> block_request=new ArrayList<String>();
            try{
                int i=0;
                while(response.next()){
                    
                    block_request.add(response.getString("nom"));
                }
                i=block_request.size();
                String[] block_list=new String[i];
                for(i=0;i<block_request.size();i++){
                    block_list[i]=block_request.get(i);
                }
                enregistrement_block.setModel(new javax.swing.DefaultComboBoxModel<>(block_list));
            }
            catch(Exception e){
                e.printStackTrace();   
            } 
        }
    }
    
    public boolean enregister(){
        SimpleDateFormat dateFormater=new SimpleDateFormat("yyyy-MM-dd");
        head[0]="nom";
        head[1]="prenom";
        head[2]="genre";
        head[3]="date_naissance";
        head[4]="tel";
        //head[5]="nom";
        
        fields[0]=enregistrement_nom.getText();
        fields[1]=enregistrement_prenom.getText();
        fields[2]=(String)enregistrement_genre.getSelectedItem();
        fields[3]=dateFormater.format(new Date(String.valueOf(enregistrement_date.getDate())));
        fields[4]=enregistrement_tel.getText();
        //fields[5]=enregistrement_motif.getText();
        
        if(C1.insert_into("patient", head, fields)){
            if(createTicket()){
                try{
                    ResultSet select =C1.simple_select("ticket");
                    select.next();
                    ResultSet bloc =C1.select_from_id("bloc",Integer.parseInt(select.getString("id_bloc")));
                    bloc.next();
                    JOptionPane.showMessageDialog(this, "Votre numero de ticket est"+select.getString("id")+select.getString("numero")+"\nDirigez vous vers le bloc "+bloc.getString("nom"), "Ticket No"+select.getString("id")+select.getString("numero"), JOptionPane.INFORMATION_MESSAGE);

                    return true;
                }
                catch(Exception e){
                    e.printStackTrace();
                    return false;
                }
            }
            else{
                return false;
            }
        }
        else{
            return false;
        }
    }  
    
    public boolean createTicket(){
        try{
            ResultSet query=catchPatient(fields[0],fields[1],fields[4]);
            if(query!=null){
                query.next();
                
                String[] ticketHead=new String[4];
                ticketHead[0]="numero";
                ticketHead[1]="motif";
                ticketHead[2]="id_bloc";
                ticketHead[3]="id_patient";
                
                String[] ticketContent=new String[4];
                ticketNumber++;
                ticketContent[0]="A"+ticketNumber;
                ticketContent[1]=enregistrement_motif.getText();
                ResultSet blockId=catchBloc((String) enregistrement_block.getSelectedItem());
                if(blockId!=null){
                    blockId.next();
                    ticketContent[2]=blockId.getString("id");
                }
                else{
                    return false;
                }
                ticketContent[3]=query.getString("id");
                if(C1.insert_into("ticket", ticketHead, ticketContent)){
                    return true;
                }
                else{
                    return false;
                }  
            }
        }
        catch(Exception e){
            e.printStackTrace();
            System.out.println("Erreur de connexion");
            return false;
        }
        return false;
    }
    
    public ResultSet catchPatient(String nom, String prenom, String tel){
        String query="SELECT * FROM patient WHERE nom=? AND prenom=? AND tel=?;";
        Object resultat=new Object();
        C1.try_connection();
        try{
            PreparedStatement stm= C1.conn.prepareStatement(query);
            stm.setString(1, nom);
            stm.setString(2, prenom);
            stm.setString(3, tel);
            resultat=(ResultSet)stm.executeQuery();
            
        }
        catch (Exception e){
            e.printStackTrace();
            System.out.println("Erreur de connexion");
            resultat=null;
        }
        return (ResultSet)resultat;
    }
    public ResultSet catchBloc(String nom){
        String query="SELECT * FROM bloc WHERE nom=?;";
        Object resultat=new Object();
        C1.try_connection();
        try{
            PreparedStatement stm= C1.conn.prepareStatement(query);
            stm.setString(1, nom);
            resultat=(ResultSet)stm.executeQuery(); 
        }
        catch (Exception e){
            e.printStackTrace();
            System.out.println("Erreur de connexion");
            resultat=null;
        }
        return (ResultSet)resultat;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> enregistrement_block;
    private javax.swing.JButton enregistrement_btn_annuler;
    private javax.swing.JButton enregistrement_btn_enregistrer;
    private com.toedter.calendar.JDateChooser enregistrement_date;
    private javax.swing.JComboBox<String> enregistrement_genre;
    private javax.swing.JTextField enregistrement_motif;
    private javax.swing.JTextField enregistrement_nom;
    private javax.swing.JTextField enregistrement_prenom;
    private javax.swing.JTextField enregistrement_tel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
